site_name: User Guide
# site_url: https://pixora.github.io/yoc-user-guide/
theme:
  name: material
  logo: assets/logo_sacs.png
  favicon: assets/favicon.png
  language: it
  palette:
    primary: white
    accent: indigo
  features:
    - navigation.expand
plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print'
      add_print_site_banner: true
      print_site_banner_template: "./docs/assets/templates/custom_banner.tpl"
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: "./docs/assets/templates/cover.tpl"
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:
